language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
# command to install dependencies
install:
  - pip install NGSpeciesID
  # - pip install coveralls
# os:
#   - linux
#   - osx
# safelist
branches:
  only:
  - master
  # - develop
# command to run tests
script: python NGSpeciesID --help 
# after_success:
#  - coveralls