language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - pip install isONclust
  # - pip install coveralls
# os:
#   - linux
#   - osx
# safelist
branches:
  only:
  - master
  # - develop
# command to run tests
script: python isONclust --isoseq --fastq test/sample_alz_2k.fastq --outfolder test/out --t 1 
# after_success:
#  - coveralls